# Generated by Django 5.2.7 on 2025-11-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('idoportunidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombreoportunidad', models.CharField(max_length=45)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_cierre_estimada', models.DateTimeField(null=True)),
                ('comentarios', models.TextField(null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_eliminacion', models.DateTimeField(null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'oportunidades',
                'managed': False,
            },
        ),
    ]
