# Generated by Django 5.2.7 on 2025-11-13 16:48

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'rol_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellidopaterno', models.CharField(max_length=45)),
                ('apellidomaterno', models.CharField(max_length=45)),
                ('numerotel', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('local_Fijo', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], db_column='local_Fijo', max_length=2, null=True)),
                ('nombre_negocio', models.CharField(blank=True, max_length=100, null=True)),
                ('nss', models.CharField(blank=True, max_length=11, null=True)),
                ('curp', models.CharField(blank=True, max_length=18, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
            managers=[
                ('activos', django.db.models.manager.Manager()),
            ],
        ),
    ]
