# Generated by Django 5.2.7 on 2025-11-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusCobros',
            fields=[
                ('idestatus_cobros', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estatus_cobro', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'estatus_cobros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtapaVentas',
            fields=[
                ('idetapa_ventas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_etapa', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'etapa_ventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventa', models.AutoField(primary_key=True, serialize=False)),
                ('claveventa', models.CharField(max_length=10, unique=True)),
                ('nombreventa', models.CharField(max_length=45)),
                ('preciototal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cfdi', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ventas',
                'managed': False,
            },
        ),
    ]
