# Generated by Django 5.2.7 on 2025-11-21 04:10

from django.db import migrations, models

def asignar_orden_inicial(apps, schema_editor):
    EtapaVentas = apps.get_model('ventas', 'EtapaVentas')

    # Orden sugerido: 1,2,3,4...
    for index, etapa in enumerate(EtapaVentas.objects.order_by('idetapa_ventas'), start=1):
        etapa.orden = index
        etapa.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]
    
    operations = [
        migrations.AlterModelOptions(
            name='etapaventas',
            options={'managed': True},
        ),
        migrations.RunPython(asignar_orden_inicial),
    ]
    
    
