# Generated by Django 5.2.7 on 2025-11-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_etapaventas_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapaventas',
            name='orden',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
