# Generated by Django 5.2.7 on 2025-11-13 16:48

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellidopaterno', models.CharField(max_length=45)),
                ('apellidomaterno', models.CharField(max_length=45)),
                ('numerotelcli', models.CharField(max_length=10)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultimocontacto', models.DateTimeField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_eliminacion', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
            managers=[
                ('activos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoClienteCat',
            fields=[
                ('idestado_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'estado_cliente_cat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrecuenciaClienteCat',
            fields=[
                ('idfrecuencia_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_frecuencia', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'frecuencia_cliente_cat',
                'managed': False,
            },
        ),
    ]
